column:
  customerID: object 
  gender: object 
  SeniorCitizen: int 
  Partner: object 
  Dependents: object 
  tenure: int
  PhoneService: object 
  MultipleLines: object 
  InternetService: object 
  OnlineSecurity: object 
  OnlineBackup: object 
  DeviceProtection: object 
  TechSupport: object 
  StreamingTV: object 
  StreamingMovies: object 
  Contract: object 
  PaperlessBilling: object 
  PaymentMethod: object 
  MonthlyCharges: float
  TotalCharges: float
  Churn: object
services:
  - PhoneService 
  - MultipleLines 
  - InternetService_used
  - OnlineSecurity 
  - OnlineBackup 
  - DeviceProtection 
  - TechSupport 
  - StreamingTV 
  - StreamingMovies 
category:
  - gender
  - tenure_group
  - PhoneService
  - MultipleLines
  - InternetService_used
  - InternetService
  - OnlineSecurity
  - OnlineBackup
  - DeviceProtection
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaperlessBilling
  - PaymentMethod
  - is_high_risk
